
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cbkmhctwwawtykbqdagz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNia21oY3R3d2F3dHlrYnFkYWd6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA4NjMzNjAsImV4cCI6MjA1NjQzOTM2MH0.CLkLELHR5qH3zfV1esNChyT2h6WedObojZgy4y6SIsc";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Define explicitly typed auth providers
export const authProviders = {
  google: 'google' as const,
  github: 'github' as const,
  facebook: 'facebook' as const,
  twitter: 'twitter' as const,
  discord: 'discord' as const,
  email: 'email' as const
};

// Authentication Functions
export const signInWithEmail = async (email: string, password: string) => {
  return await supabase.auth.signInWithPassword({
    email,
    password
  });
};

export const signInWithProvider = async (provider: 'google' | 'github' | 'facebook' | 'twitter' | 'discord') => {
  return await supabase.auth.signInWithOAuth({
    provider: provider,
    options: {
      redirectTo: window.location.origin
    }
  });
};

export const signUp = async (email: string, password: string) => {
  return await supabase.auth.signUp({
    email,
    password,
    options: {
      emailRedirectTo: window.location.origin
    }
  });
};

export const signOut = async () => {
  return await supabase.auth.signOut();
};

export const getCurrentUser = async () => {
  const { data } = await supabase.auth.getUser();
  return data.user;
};

export const getSession = async () => {
  const { data } = await supabase.auth.getSession();
  return data.session;
};

// Expose our RPC functions with proper typing
export const getUserPoints = async (userId: string): Promise<number> => {
  const { data, error } = await supabase.rpc('get_user_points', { user_id_param: userId });
  if (error) throw error;
  return data || 0;
};

export const getUserSpinHistory = async (userId: string, limit = 30): Promise<any[]> => {
  const { data, error } = await supabase.rpc('get_user_spin_history', { 
    user_id_param: userId,
    limit_count: limit
  });
  if (error) throw error;
  return data || [];
};

export const getLeaderboard = async (limit = 5): Promise<any[]> => {
  const { data, error } = await supabase.rpc('get_leaderboard', { limit_count: limit });
  if (error) throw error;
  return data || [];
};

export const saveSpinResult = async (
  userId: string, 
  prizeId: string, 
  pointsEarned = 0
): Promise<void> => {
  const { error } = await supabase.rpc('save_spin_result', {
    user_id_param: userId,
    premio_id_param: prizeId,
    points_earned_param: pointsEarned
  });
  if (error) throw error;
};
