
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cbkmhctwwawtykbqdagz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNia21oY3R3d2F3dHlrYnFkYWd6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA4NjMzNjAsImV4cCI6MjA1NjQzOTM2MH0.CLkLELHR5qH3zfV1esNChyT2h6WedObojZgy4y6SIsc";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
